spring:
  datasource:
     url: jdbc:postgresql://ep-shrill-mode-a2dweaax.eu-central-1.aws.neon.tech/quizapp?user=quizapp_owner&password=8NDErcdjyM5C&sslmode=require
    username: quizapp_owner
    password: 8NDErcdjyM5C

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
