spring:
  datasource:
    url: jdbc:postgresql://ep-raspy-cell-a2mfz8ll.eu-central-1.aws.neon.tech/quizapp?sslmode=require
    username: quizapp_owner
    password: 8NDErcdjyM5C
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
